### ISSUE TITLE
Protocol version

### ISSUE THREAD

**Issue by maxiko** [TvdW/perl-DBD-Cassandra#16]
Add the ability to change protocol_version. As I think this driver support only protocol version 3.

**Comment by TvdW** [comment]
Right now the driver uses the lowest currently supported protocol version (v3), because we don't use any features newer protocol versions add.

Cassandra 2.1, which is the lowest Cassandra version to support protocol version 3, went EOL a while ago and has now stopped receiving critical updates as well (as of two days ago). I don't plan to support it.

As for future versions of Cassandra: the aim is to keep compatibility with all _supported_ (by Apache) Cassandra versions. However, as long as there's no feature we need, there's no point in advertising a higher protocol version than we actually use.

If you have any feature you'd like, please file a request for that instead (or a pull request, please :)).
