### ISSUE TITLE
Failure when inserting timestamps

### ISSUE THREAD

**Issue by perljedi** [TvdW/perl-DBD-Cassandra#6]
Hi,

I was very happy to see this module on CPAN, thank you for writing it.

I am however having an issue inserting values in to a timestamp column.  I have tried formatting my timestamp in several of formats that cassandra accepts and I am getting errors on insert like:

```
Argument "2016-07-15 18:23:13" isn't numeric in pack at (eval 442) line 9.
```

**Comment by TvdW** [comment]
For performance reasons, but also because it's closer to the Perl idiom, DBD::Cassandra uses timestamps in the "milliseconds since the unix epoch" format. This is the format returned by time(), multiplied by 1000. For example, to insert the current time, you would use `time()*1000`.

If you want to convert these from/to human readable formats, you can use the DateTime library. Example :

```
use DateTime;
my $dbh= DBI->connect('dbi:Cassandra:...');
my $now= DateTime->now;
$dbh->do('insert into table (id, time) values (?, ?)', undef, 1, ($now->hires_epoch()*1000));
my $rows= $dbh->selectall_arrayref('select * from table where id=?', undef, 1);
for my $row (@$rows) {
    say DateTime->from_epoch($row->[0]);
}
```

**Comment by perljedi** [comment]
Hi,

Thanks for the response.  I did figure out the work around, and its fine for my needs.  I would however you suggest you document this limitation.

**Comment by TvdW** [comment]
Fair point. Will add that to the documentation in the next release.
